[package]
name = "Nal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
#rc4 = "0.1.0"
log = "0.4.20"
async-trait = "0.1.77"
cron = "0.12.1"
chrono = "0.4.34"
#env_logger = "0.11.3"
#fern = "0.6"
log4rs = "1.3.0"
yaml-rust = "0.4.5"
service-manager = "0.6.1"
clap = { version = "4.5.4", features = ["derive"] }
clap_derive = "4.5.4"
